### ISSUE TITLE
Memory leak in TCPInterface.cpp

### ISSUE THREAD

**Issue by Tomash667** [SLikeSoft/SLikeNet#18]
incomingMessages is cleared in Stop but it contains data allocated with rakMalloc_Ex. 

My solution:
```
for(i = 0; i < incomingMessages.Size(); ++i)
		rakFree_Ex(incomingMessages[i]->data, _FILE_AND_LINE_);
before
incomingMessages.Clear(_FILE_AND_LINE_);
```

When this happen?
When HTTPConnection receive response in background thread but is closed before calling TCPInterface Receive.

**Comment by Luke1410** [comment]
Thanks for the report.
Assigned internal case number SLNET-125 for investigation.

**Comment by Luke1410** [comment]
Issue was confirmed and fixed (slightly different than your proposed solution, though atm based on the current implementation your solution works as fine as the one we ended up with).

The fix is already available in the SVN and GitHub repositories and should be available in SLikeNet 0.1.1.

**Comment by Luke1410** [comment]
Given that you did all of the analysis work and also provided a working patch, we'd like to give you credit in the readme.txt file for this fix. If you are fine with that, pls send a quick mail to info [at] slikesoft [dot] com and/or reply via a comment here.

If you like, you can also acknowledge/accept our CLA so that we can directly incorporate any future contributions from you directly. See https://github.com/SLikeSoft/SLikeNet/blob/master/.github/CONTRIBUTING.md for the CLA.

**Comment by Luke1410** [comment]
SLikeNet 0.1.1 which contains this fix has just been released.

**Comment by Luke1410** [comment]
Reclassified as a low to medium security vulnerability. The issue can (at least in theory) be utilized to run DoS-attacks. The vulnerability is in our opinion however quite limited because:
a) it only applies for cases using a TCP connection
b) it's defined by conditions which are hardly controllable by the attacker (i.e. depends on when the server terminates a TCP connection and whether the retrieved data was already processed)

Still, a persistent attacker could utilize this issue to eventually cause a server to run out of memory and ultimately make the server unavailable.

CVSS Base score: 5.3
CVSS Temporal score: 4.8
CVSS Overall score: 4.8
CVSS v3 Vector: AV:N/AC:H/PR:L/UI:N/S:U/C:N/I:N/A:H/E:P/RL:O/RC:C
