### ISSUE TITLE
Semantic Versioning of 2.0.x

### ISSUE THREAD

**Issue by Nopey** [SLikeSoft/SLikeNet#22]
Currently SLikeNet is somewhere near version 0.1.0
Unless there is an API breaking version I've missed, the API breaking changes should be named 1.0.x, and not 2.0.x

**Comment by Luke1410** [comment]
I'm not sure I can follow you. SLikeNet is currently in a development state which is reflected by the pre-1.0-version number.

From the semantic versioning specification [1]:
"4. Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable."

Our readme further explains that the current version number (see section 1.2.1). It states that:
"[...] Furthermore, since our aim for SikeNet 1.0.0 is to keep ABI/API/Protocol compatibility with RakNet 4.081/4.082, we consider the API/ABI/Protocol of the 0.x.y release already stable and [...]"

So, yes, we could declare the current version from that point of view already 1.0.0, but we think we are certainly not there yet and still have a certain amount of work left to do.

Still, if you are worried about API/ABI compatibility, our statement stands. We consider the development version already quite stable in this regards, though the 0.2.0 version is likely to contain some API/ABI fixes to resolve some (minor) API/ABI breakage (compared to RakNet) which sneaked in in the initial version.

Does this answer your question, or did I get your point wrong?

[1] = http://semver.org/

**Comment by Nopey** [comment]
Your explanation cleared things up, thanks for the quick reply!
