### ISSUE TITLE
Bug: ReadCompressed() method in bitstream class 

### ISSUE THREAD

**Issue by Kiddinglife** [SLikeSoft/SLikeNet#23]
the bug is it does not tell little endian and big endian.
I will create a pull request for this bug

**Comment by Luke1410** [comment]
Corresponding PR: #26

**Comment by Luke1410** [comment]
As discussed in the linked PR, this is not a bug, since the two methods referred to are private BitStream()-helpers used by the public Read/WriteCompressed() methods. The private ones have the prerequisite of being given already "normalized" (i.e. native) endian data, which all the callers correctly ensure. Therefore, this is not a bug.

The corresponding PR however contains some nice ideas for improvements, which we'll review separately at one point.

Hence closing this issue, but leaving the PR open.
